[package]
name = "jetbrains_intership"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.9.5"
hex = "0.4.3"
core_crate = { path = "core_crate" }
data_manager = { path = "data_manager" }
server_communicator = { path = "server_communicator" }
http_message = { path = "http_message" }
